run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - gosimple
    - unused
    - ineffassign
  disable:
    - gocyclo
    - gomnd

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters-settings:
  gofmt:
    simplify: true
